export const constellationStars = [
  {
    id: 'star-1',
    name: 'Buddy',
    type: 'Golden Retriever 🐕',
    years: '2012 - 2026',
    tribute: 'Run free across the endless golden stars, forever loyal and true.',
    stage: 2,
    x: 28,
    y: 28,
    color: '#FFDE7A',
    likes: 14,
    temple: 'Wat Khlong Toei Nai Sanctuary'
  },
  {
    id: 'star-2',
    name: 'Luna',
    type: 'Persian White Cat 🐈',
    years: '2015 - 2026',
    tribute: 'Our quiet moonbeam. Your gentle purr will always warm the night sky.',
    stage: 2,
    x: 74,
    y: 22,
    color: '#FFDE7A',
    likes: 9,
    temple: 'Boudha Stupa Memorial Grove'
  },
  {
    id: 'star-3',
    name: 'Max',
    type: 'French Bulldog 🐾',
    years: '2017 - 2026',
    tribute: 'Little body, biggest heart in the universe. Thank you for infinite joy.',
    stage: 2,
    x: 24,
    y: 56,
    color: '#FFDE7A',
    likes: 21,
    temple: 'Swayambhu Peace Temple Rites'
  },
  {
    id: 'star-4',
    name: 'Bella',
    type: 'Pomeranian Cloud 🐩',
    years: '2016 - 2026',
    tribute: 'The sweetest little cloud of happiness. Shine brightly in our constellation.',
    stage: 2,
    x: 74,
    y: 50,
    color: '#FFDE7A',
    likes: 12,
    temple: 'Wat Klong Toey Nai'
  },
  {
    id: 'star-5',
    name: 'Charlie',
    type: 'Beagle Scout 🐕',
    years: '2014 - 2026',
    tribute: 'Always chasing adventures across the meadows of eternity.',
    stage: 4,
    x: 46,
    y: 16,
    color: '#FFDE7A',
    likes: 17,
    temple: 'Pashupatinath Temple Sanctuary'
  },
  {
    id: 'star-6',
    name: 'Milo',
    type: 'Scottish Fold 🐈',
    years: '2018 - 2026',
    tribute: 'Curled up forever in our hearts. Rest in celestial peace.',
    stage: 4,
    x: 68,
    y: 36,
    color: '#FFDE7A',
    likes: 8,
    temple: 'Boudha Stupa Memorial Grove'
  },
  {
    id: 'star-7',
    name: 'Daisy',
    type: 'Cockatiel Angel 🦜',
    years: '2019 - 2026',
    tribute: 'Your cheerful morning melodies now serenade the heavens.',
    stage: 4,
    x: 16,
    y: 44,
    color: '#FFDE7A',
    likes: 6,
    temple: 'Wat Pha Suk Maneechak'
  },
  {
    id: 'star-8',
    name: 'Rocky',
    type: 'German Shepherd 🐕',
    years: '2013 - 2026',
    tribute: 'Our steadfast guardian. Watching over us from the brightest stars.',
    stage: 4,
    x: 72,
    y: 64,
    color: '#FFDE7A',
    likes: 29,
    temple: 'Pashupatinath Temple Sanctuary'
  },
  {
    id: 'star-9',
    name: 'Coco',
    type: 'Chocolate Lab 🐾',
    years: '2015 - 2026',
    tribute: 'Splashing in celestial rivers, forever joyful and free.',
    stage: 4,
    x: 30,
    y: 68,
    color: '#FFDE7A',
    likes: 15,
    temple: 'Swayambhu Peace Temple Rites'
  },
  {
    id: 'star-10',
    name: 'Lucy',
    type: 'Calico Angel 🐱',
    years: '2016 - 2026',
    tribute: 'A gentle spirit whose love will never fade from our family.',
    stage: 4,
    x: 64,
    y: 76,
    color: '#FFDE7A',
    likes: 11,
    temple: 'Wat Klong Toey Nai'
  }
];
